### ISSUE TITLE
Not building on Netlify or Vercel...

### ISSUE THREAD

**Issue by rchrdnsh** [thecodejack/svelte-file-dropzone#134]
Getting the follow error when building on Netlify and Vercel:

```
[commonjs--resolver] Failed to resolve entry for package "svelte-file-dropzone". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "svelte-file-dropzone" package
error during build:
Error: Failed to resolve entry for package "svelte-file-dropzone". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "svelte-file-dropzone" package
    at packageEntryFailure (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/vite/dist/node/chunks/dep-1f986b87.js:23382:11)
    at resolvePackageEntry (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/vite/dist/node/chunks/dep-1f986b87.js:23377:9)
    at tryNodeResolve (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/vite/dist/node/chunks/dep-1f986b87.js:23113:20)
    at Object.resolveId (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/vite/dist/node/chunks/dep-1f986b87.js:22874:28)
    at Object.handler (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/vite/dist/node/chunks/dep-1f986b87.js:46681:19)
    at file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/rollup/dist/es/shared/node-entry.js:24592:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/rollup/dist/es/shared/node-entry.js:24492:28)
    at async resolveId (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/rollup/dist/es/shared/node-entry.js:23389:26)
    at async ModuleLoader.resolveId (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/rollup/dist/es/shared/node-entry.js:23653:15)
    at async Object.resolveId (file:///Users/rchrdnsh/Code/Svelte/__active-projects/RYKR/node_modules/vite/dist/node/chunks/dep-1f986b87.js:7990:10)
```

**Comment by rchrdnsh** [comment]
ah! nevermind...I had it imported the old way on some random page in the app...works fine now.
