### ISSUE TITLE
Error: Missing "./Dropzone.svelte" specifier in "svelte-file-dropzone" package

### ISSUE THREAD

**Issue by bluepuma77** [thecodejack/svelte-file-dropzone#155]
Just updated to the new patch release, but now SvelteKit will throw an error:

```
[plugin:vite:import-analysis] Missing "./Dropzone.svelte" specifier in "svelte-file-dropzone" package

/home/projects/sveltejs-kit-template-default-j2hn7c/src/routes/+page.svelte

    at e (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21960:25)
    at n (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21960:627)
    at o (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:21960:1297)
    at resolveExportsOrImports (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29512:22)
    at resolveDeepImport (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29531:54)
    at tryNodeResolve (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29256:20)
    at resolveId (/home/projects/sveltejs-kit-template-default-j2hn7c/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:29024:28
```

To reproduce:
1. Go to https://sveltekit.new
2. Use `+` to open additional terminal and enter `npm install svelte-file-dropzone`
3. Add `import Dropzone from "svelte-file-dropzone/Dropzone.svelte"` to any `.svelte` file

Strangely the error does not go away when downgrading locally. And it happens on the official REPL.

**Comment by bluepuma77** [comment]
Solution: change
```
    import Dropzone from "svelte-file-dropzone/Dropzone.svelte";
```
to
```
    import Dropzone from "svelte-file-dropzone";
```
in the README.md "Usage" section.

This is kind of a breaking change, according to server it should be v3.0.0.

**Comment by arackaf** [comment]
Yeah, `import Dropzone from "svelte-file-dropzone";` is the solution. In theory 2.0.2 should have been a major release since it broke that.

Closing this since it looks like you have your solution.
