### ISSUE TITLE
Failed to resolve import "$app/env"

### ISSUE THREAD

**Issue by mishantrop** [thecodejack/svelte-file-dropzone#95]
```
[vite] Internal server error: Failed to resolve import "$app/env" from "node_modules/svelte-file-dropzone/src/components/Dropzone.svelte". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/user/projects/foo/node_modules/svelte-file-dropzone/src/components/Dropzone.svelte
  26 |  } from "svelte/internal";
  27 |  
  28 |  import { browser } from "$app/env";
     |                           ^
  29 |  import { fromEvent } from "file-selector";
  30 |  
      at formatError (/home/user/projects/foo/node_modules/vite/dist/node/chunks/dep-611778e0.js:36296:46)
      at TransformContext.error (/home/user/projects/foo/node_modules/vite/dist/node/chunks/dep-611778e0.js:36292:19)
      at normalizeUrl (/home/user/projects/foo/node_modules/vite/dist/node/chunks/dep-611778e0.js:59668:26)
      at async TransformContext.transform (/home/user/projects/foo/node_modules/vite/dist/node/chunks/dep-611778e0.js:59817:57)
      at async Object.transform (/home/user/projects/foo/node_modules/vite/dist/node/chunks/dep-611778e0.js:36533:30)
      at async doTransform (/home/user/projects/foo/node_modules/vite/dist/node/chunks/dep-611778e0.js:55507:29)
```

Project: https://github.com/mishantrop/yet-another-package-json-dependencies-updates-checker-frontend

How to reproduce:
- Uncomment import and usage of Dropzone component
https://github.com/mishantrop/yet-another-package-json-dependencies-updates-checker-frontend/blob/main/src/Form.svelte

**Comment by thecodejack** [comment]
Hi..this is at present happening with dev version only of v1. Please avoid same. This was added for SSR compatibility with sveltekit. Will be working on fix once available to handle same.

**Comment by carbogninalberto** [comment]
any update?

**Comment by thecodejack** [comment]
@carbogninalberto using <1 version can avoid the issue. Infact v1 versions so far released are dev versions only.

**Comment by thecodejack** [comment]
have release v1 which should fix the issue. Please reopen if found otherwise.
